name: Security Analysis

on:
  push:
    branches: [ main ]
  pull_request:

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_PATH: 'DictApp/DataDictGen.sln'

jobs:
  security-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Paso 1: Restaurar dependencias para que Snyk pueda analizarlas
      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      # Paso 2: Analizar con Snyk (versión corregida)
      - name: Run Snyk analysis
        uses: snyk/actions/dotnet@master
        with:
          command: test
          args: --all-projects --file=${{ env.SOLUTION_PATH }} --json-file-output=snyk-results.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Generar reporte HTML
      - name: Generate Snyk report
        if: success() || failure()  # Ejecuta siempre
        run: |
          npm install -g snyk-to-html
          if [ -f "snyk-results.json" ]; then
            snyk-to-html -i snyk-results.json -o snyk-report.html
          else
            echo '{"vulnerabilities": []}' > snyk-report.html
          fi

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: snyk-report.html
