name: Security Analysis
env:
  DOTNET_VERSION: '8.x'
on: push
permissions:
  contents: read
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Semgrep Analysis
      - name: Run Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/default
          output: semgrep-report.json

      - name: Convert Semgrep to HTML
        run: |
          python -m pip install prospector2html
          prospector-html --input semgrep-report.json --output public/reports/semgrep-report.html

      # Snyk Analysis
      - uses: snyk/actions/setup@master
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Run Snyk Test
        run: |
          npm install -g snyk-to-html
          snyk code test --json | snyk-to-html -o public/reports/snyk-report.html
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: public/reports/
