name: Security Analysis

env:
  DOTNET_VERSION: '8.x'

on: push

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Semgrep Analysis - Versión corregida
      - name: Run Semgrep Scan
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/default
          output_file: semgrep-results.json
          sarif: false

      - name: Verify Semgrep output
        run: |
          ls -la
          if [ -f "semgrep-results.json" ]; then
            echo "Semgrep file exists"
            cat semgrep-results.json | jq empty
          else
            echo "Semgrep file NOT found!"
            exit 1
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install prospector2html
          sudo apt-get install -y jq  # Para validar JSON

      - name: Convert to HTML
        run: |
          prospector-html \
            --input semgrep-results.json \
            --output public/semgrep-report.html \
            --filter semgrep

      # Snyk Analysis (se mantiene igual)
      - uses: snyk/actions/setup@master
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Run Snyk test
        run: |
          npm install -g snyk-to-html
          snyk code test --json > snyk-results.json
          snyk-to-html -i snyk-results.json -o public/snyk-report.html
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: public/
